module.exports = {
  DATA: {
    EVENTS: {
      ADVANCE:'advance',
      BROADCAST_MESSAGE: 'broadcastMessage',
      CHAT: 'chat',
      CHAT_COMMAND: 'chatCommand',
      DELETE_CHAT: 'deleteChat',
      DJ_QUEUE_ADD: 'djQueueModAdd',
      DJ_QUEUE_CYCLE: 'djQueueCycle',
      DJ_QUEUE_LIMIT: 'djQueueLimit',
      DJ_QUEUE_LOCK: 'djQueueLock',
      DJ_QUEUE_MOD_MOVE: 'djQueueModMove',
      DJ_QUEUE_MOD_SKIP: 'djQueueModSkip',
      DJ_QUEUE_MOD_SWAP: 'djQueueModSwap',
      DJ_QUEUE_REMOVE: 'djQueueModRemove',
      DJ_QUEUE_SKIP: 'djQueueSkip',
      PRIVATE_MESSAGE: 'privateMessage',
      SERVER_RESPONSE: 'response',
      SYSTEM_MESSAGE: 'systemMessage',
      USER_BANNED: 'userBanned',
      USER_JOINED: 'userJoined',
      USER_JOINED_QUEUE: 'userJoinedQueue',
      USER_LEFT: 'userLeft',
      USER_LEFT_QUEUE: 'userLeftQueue',
      USER_ROLE_CHANGE: 'moderateSetRole',
      USER_UNBANNED: 'userUnbanned',
      USER_UPDATE: 'userUpdate',
      VOTE_UPDATE: 'voteUpdate',
    },
  },
};
